sonar.projectKey=zaphiro-technologies_license-checker
sonar.organization=zaphiro-technologies
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.test.*, **/*.spec.*, **/tests/**, **/*.xml, **/*.md, **/*.sql, .github/**, public/**, dist/**, coverage/**, node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
